[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#2aa198"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.end]
background = "#282a36"
foreground = "#f1fa8c"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#282a36"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#6c71c4"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#000e13"
bright_foreground = "#ffffff"
foreground = "#839496"

[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[colors.selection]
background = "#44475a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 12.0

[font.bold]
family = "BerkeleyMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "BerkeleyMonoNerdFont"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "BerkeleyMonoNerdFont"
style = "Italic"

[font.normal]
family = "BerkeleyMonoNerdFont"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
# live_config_reload = true
opacity = 0.9
# save_to_clipboard = true
# semantic_escape_chars = ''',│`|:"' ()[]{}<>'''
# startup_mode = "Fullscreen"

[window.padding]
x = 2
y = 2

[keyboard]
