format = """\
[ 󰀵 ](fg:#073642 bg:#eee8d5 bold)\
[](fg:#eee8d5 bg:#93a1a1)\
$time\
[](fg:#93a1a1 bg:#002b36)\
$directory\
[](fg:#002b36 bg:#586e75)\
$git_branch\
[](fg:#586e75)\
$git_status\
$character\
"""

[directory]
format = "[ ﱮ $path ]($style)"
style = "fg:#93a1a1 bg:#002b36"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#eee8d5 bg:#586e75"

[git_status]
format = "[ $all_status ]($style)"

# [git_metrics]
# format = "[ +$added ]($added_style)[ -$deleted ]($deleted_style)"
# added_style = "fg:#b58900"
# deleted_style = "fg:#dc322f"
# disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:#93a1a1 bg:#002b36"

[character]
success_symbol = "[ ➜ ](fg:#93a1a1 bold) "
error_symbol = "[ ✗ ](fg:#dc322f bold) "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#15161e bg:#93a1a1"
format = "[ 󱑍 $time ]($style)"
