# $HOME/.config/alacritty/alacritty.toml
# by Tiankai Xie

[window]

opacity = 0.95


decorations = "Transparent"
decorations_theme_variant = "Dark" # "Dark"
blur = true
dynamic_padding = true

startup_mode = "SimpleFullscreen"

[font]

normal.family = "BerkeleyMonoNerdFont"
bold.family = "BerkeleyMonoNerdFont"
italic.family = "BerkeleyMonoNerdFont"
bold_italic.family = "BerkeleyMonoNerdFont"

size = 14.0

# Tip: for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a 
# small box when a HEX is detected by the editor.

[colors]

primary.background = "#0E1516"
primary.foreground = "#869395"
